<?php

/**
 * @file
 * Contains df_tools_editor.module.
 */

use Drupal\editor\Entity\Editor;

/**
 * Implements hook_modules_installed().
 *
 * Adds Lite module buttons to the rich_text format.
 */
function df_tools_editor_modules_installed($modules) {
  /** @var \Drupal\editor\EditorInterface $editor */
  $editor = Editor::load('rich_text');

  if ($editor) {
    // Retrieve the editor settings for the Rich Text format.
    $settings = $editor->getSettings();

    // If a group of 'Track Changes' buttons is enabled, return.
    foreach ($settings['toolbar']['rows'] as $row) {
      foreach ($row as $group) {
        if ($group['name'] == 'Track Changes') {
          return;
        }
      }
    }

    // Define a group of 'Track Changes' buttons.
    $lite = [
      'name' => 'Track Changes',
      'items' => [
        'lite-acceptall',
        'lite-acceptone',
        'lite-rejectone',
        'lite-toggleshow',
        'lite-rejectall',
      ],
    ];

    // Tack the 'Track Changes' group onto the end of the first toolbar row.
    $settings['toolbar']['rows'][0][] = $lite;
    $editor->setSettings($settings)->save();
  }
}

/**
 * Implements hook_libraries_info_alter().
 *
 * The LITE plugin does not currently handle custom HTML tags such as
 * `<drupal-entity>` and `<drupal-url>`.
 * The plugin must be patched to ignore custom tags until the issue is fixed.
 * Unfortunately, the version hosted on ckeditor.com is minified making patching
 * impossible. Therefore, in order to work around the issue, we use the raw
 * source files from Github which use a different directory structure.
 */
function df_tools_editor_libraries_info_alter(&$libraries) {
  // The raw source files hosted on Github are located in a subdirectory.
  if (!empty($libraries['lite'])) {
    $libraries['lite']['path'] = 'src/lite';

    // Reset the library path to work around a bug with the Libraries module not
    // incorporating the ['path'] when calling libraries_get_path().
    $libraries['lite']['library path'] = libraries_get_path('lite') . '/' . $libraries['lite']['path'];

    // Hardcode the version number because the raw source files do not contain
    // any version information.
    $libraries['lite']['version'] = '1.2.26';
  }
}

/**
 * Implements hook_ckeditor_plugin_info_alter().
 */
function df_tools_editor_editor_js_settings_alter(array &$settings) {
  foreach ($settings['editor']['formats'] as &$format) {
    // Swap in our custom JS by adding a pseudo plugin. We do this as we do not
    // provide a button, which is what traditional CKEditor plugins would do.
    $format['editorSettings']['drupalExternalPlugins']['df_tools_editor'] = base_path() . drupal_get_path('module', 'df_tools_editor') . '/js/df_tools_editor.js';
    $format['editorSettings']['extraPlugins'] .= ',df_tools_editor';
  }
}
