<?php

/**
 * @file
 * Contains df_tools_editor.module.
 */

/**
 * Implements hook_libraries_info_alter().
 *
 * The LITE plugin does not currently handle custom HTML tags such as
 * `<drupal-entity>` and `<drupal-url>`.
 * The plugin must be patched to ignore custom tags until the issue is fixed.
 * Unfortunately, the version hosted on ckeditor.com is minified making patching
 * impossible. Therefore, in order to work around the issue, we use the raw
 * source files from Github which use a different directory structure.
 */
function df_tools_editor_libraries_info_alter(&$libraries) {
  // The raw source files hosted on Github are located in a subdirectory.
  if (!empty($libraries['lite'])) {
    $libraries['lite']['path'] = 'src/lite';

    // Reset the library path to work around a bug with the Libraries module not
    // incorporating the ['path'] when calling libraries_get_path().
    $libraries['lite']['library path'] = libraries_get_path('lite') . '/' . $libraries['lite']['path'];

    // Hardcode the version number because the raw source files do not contain
    // any version information.
    $libraries['lite']['version'] = '1.2.26';
  }
}

/**
 * Implements hook_ckeditor_plugin_info_alter().
 */
function df_tools_editor_editor_js_settings_alter(array &$settings) {
  foreach ($settings['editor']['formats'] as &$format) {
    // Swap in our custom JS by adding a pseudo plugin. We do this as we do not
    // provide a button, which is what traditional CKEditor plugins would do.
    $format['editorSettings']['drupalExternalPlugins']['df_tools_editor'] = base_path() . drupal_get_path('module', 'df_tools_editor') . '/js/df_tools_editor.js';
    $format['editorSettings']['extraPlugins'] .= ',df_tools_editor';
  }
}
