<?php

/**
 * @file
 * Hooks and functions of df_tools_media_video.module.
 */

use Drupal\Core\Template\Attribute;

/**
 * Implements hook_theme().
 */
function df_tools_media_video_theme() {
  return [
    'media_video_file_formatter__df_tools_media' => [
      'base hook' => 'media_video_file_formatter',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK_alter() for media_video_file_formatter.
 */
function df_tools_media_video_theme_suggestions_media_video_file_formatter_alter(array &$suggestions, array $variables, $hook) {
  $suggestions[] = 'media_video_file_formatter__df_tools_media_video';
}

/**
 * Implements template_preprocess_HOOK() for media_video_file_formatter.
 */
function df_tools_media_video_preprocess_media_video_file_formatter__df_tools_media_video(&$variables) {
  // By default, 'extravalue' contains a string. If the HMTL5 video formatter
  // has some attributes with values, special chars (like double comma) will be
  // escaped.
  // To fix this, we replace 'extravalue' with a properly set Twig Attribute
  // object and properly update the 'attribute' array as well.
  $attribute = new Attribute();
  if (!empty($variables['extravalue'])) {
    $attributes_raw = explode(' ', trim($variables['extravalue']));

    foreach ($attributes_raw as $attribute_raw) {
      if (($delimiter_pos = strpos($attribute_raw, '=')) !== FALSE) {
        $key = substr($attribute_raw, 0, $delimiter_pos);
        $value = trim(substr($attribute_raw, ($delimiter_pos + 1)), " \"\t\n\r\0\x0B");

        if (!in_array($value, ['true', 'TRUE'])) {
          $variables['attributes'][$key] = $value;
          $attribute->setAttribute($key, $value);
          continue;
        }
      }

      $variables['attributes'][$attribute_raw] = TRUE;
      $attribute->setAttribute($attribute_raw, TRUE);
    }
  }

  $variables['extravalue'] = $attribute;
}
