<?php

/**
 * @file
 * Contains df_tools_events.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function df_tools_events_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the df_tools_events module.
    case 'help.page.df_tools_events':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Defines Event content type for use in demos.') . '</p>';
      return $output;

    default:
  }
}
