<?php
/**
 * @file
 * Code for the DF Import feature.
 */

include_once 'df_import.features.inc';

/**
 * Implements hook_migrate_api().
 */
function df_import_migrate_api() {
  $api = array(
    'api' => 2,
    'migrations' => array(
      'DemoFrameworkBaseGroups' => array('class_name' => 'DemoFrameworkBaseGroups'),
      'DemoFrameworkBaseNodes' => array('class_name' => 'DemoFrameworkBaseNodes'),
      'DemoFrameworkBaseNodesGroup' => array('class_name' => 'DemoFrameworkBaseNodesGroup'),
      'DemoFrameworkBaseNodesTranslations' => array('class_name' => 'DemoFrameworkBaseNodesTranslations'),
      'DemoFrameworkBaseProducts' => array('class_name' => 'DemoFrameworkBaseProducts'),
      'DemoFrameworkBaseCommerceNodes' => array('class_name' => 'DemoFrameworkBaseCommerceNodes'),
      'DemoFrameworkBaseTerms' => array('class_name' => 'DemoFrameworkBaseTerms'),
      'DemoFrameworkBaseUserPictures' => array('class_name' => 'DemoFrameworkBaseUserPictures'),
      'DemoFrameworkBaseUsers' => array('class_name' => 'DemoFrameworkBaseUsers'),
    ),
  );
  return $api;
}

