<?php
/**
 * @file
 * Code for the DF Import feature.
 */

include_once 'df_import.features.inc';

/**
 * Implements hook_migrate_api().
 */
function df_import_migrate_api() {
  $api = array(
    'api' => 2,
    'migrations' => array(
      'DemoFrameworkBaseGroups' => array('class_name' => 'DemoFrameworkBaseGroups'),
      'DemoFrameworkBaseNodes' => array('class_name' => 'DemoFrameworkBaseNodes'),
      'DemoFrameworkBaseNodesGroup' => array('class_name' => 'DemoFrameworkBaseNodesGroup'),
      'DemoFrameworkBaseNodesTranslations' => array('class_name' => 'DemoFrameworkBaseNodesTranslations'),
      'DemoFrameworkBaseProducts' => array('class_name' => 'DemoFrameworkBaseProducts'),
      'DemoFrameworkBaseCommerceNodes' => array('class_name' => 'DemoFrameworkBaseCommerceNodes'),
      'DemoFrameworkBaseTerms' => array('class_name' => 'DemoFrameworkBaseTerms'),
      'DemoFrameworkBaseUserPictures' => array('class_name' => 'DemoFrameworkBaseUserPictures'),
      'DemoFrameworkBaseUsers' => array('class_name' => 'DemoFrameworkBaseUsers'),
    ),
  );
  return $api;
}

/**
 * Implementation of hook_menu().
 */
function df_import_menu() {
  $items['admin/config/system/df/enable/%'] = array(
    'page callback' => 'df_import_page_enable',
    'page arguments' => array(5),
    'access arguments' => array('administer demo framework'),
    'type' => MENU_CALLBACK,
    'file' => 'df_import.enable.inc',
  );
  return $items;
}

/**
 * Implements hook_block_info().
 */
function df_import_block_info() {
  $blocks = array();
  $blocks['dfs_block'] = array(
    'info' => t('Demo Framework Scenarios'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function df_import_block_view($delta='') {
  $block = array();
  switch($delta) {
    case 'dfs_block' :
      $block['subject'] = t('Scenarios');
      $block['content'] = df_import_dfs_block_view();
      break;
  }
  return $block;
}

/**
 * Assemble render array for block content.
 * @return
 *   returns renderable array of block content.
 */
function df_import_dfs_block_view() {
  $list = '';
  $modules = system_rebuild_module_data();
  foreach ($modules as $name => $module) {
    if (substr($name, 0, 4) == 'dfs_') {
      $list .= '<li><details><summary>' . t($module->info['name']) . ' (' . _df_import_dfs_link($module) .  ')</summary>' . t($module->info['description']) . '</details></li>';
    }
  }
  $block = array(
    'scenarios' => array(
      '#type' => 'markup',
      '#prefix' => '<ul>',
      '#markup' => $list,
      '#suffix' => '</ul>',
    ),
  );
  return $block;
}

/**
 * Psuedo-private function used by 'view' "method" df_import_dfs_block_view.
 * @return
 *   returns a string of text including a link.
 */
function _df_import_dfs_link($module) {
  $action = (!module_exists($module->name) ? 'enable' : 'reset');
  $path = 'admin/config/system/df/' . $action  . '/' . $module->name;
  return  l(t(ucwords($action)), $path);
}

