api = 2
core = 8.x

; Drupal Core
projects[drupal][type] = "core"
projects[drupal][version] = "8.2.6"
projects[drupal][patch][] = "https://www.drupal.org/files/issues/node-migration-traits-database-exception-2703669-3.patch"
projects[drupal][patch][] = "https://www.drupal.org/files/issues/2635712-14.patch"
projects[drupal][patch][] = "https://www.drupal.org/files/issues/refreshless-alpha3-core-patch-2695717-7.patch"
projects[drupal][patch][] = "https://www.drupal.org/files/issues/1356276-249.patch"
projects[drupal][patch][] = "https://www.drupal.org/files/issues/2684873-28.patch"
projects[drupal][patch][] = "https://www.drupal.org/files/issues/quickedit-image-2421427-125.patch"
projects[drupal][patch][] = "https://www.drupal.org/files/issues/core-hotfix-2788277-3.patch"
projects[drupal][patch][] = "https://www.drupal.org/files/issues/quickedit-undefined-attr-2661880-14.patch"
projects[drupal][patch][] = "https://www.drupal.org/files/issues/outside-in-early-event-binding-fix-2831924-5.patch"
projects[drupal][patch][] = "https://www.drupal.org/files/issues/migrate-opcache-missing-class-2776235.patch"
projects[drupal][patch][] = "https://www.drupal.org/files/issues/allow-2681947-20_0.patch"
projects[drupal][patch][] = "https://www.drupal.org/files/issues/2830036-17.patch"
projects[drupal][patch][] = "https://www.drupal.org/files/issues/2652850-17.patch"
projects[drupal][patch][] = "https://www.drupal.org/files/issues/quickedit-render-field-attachments.patch"
projects[drupal][patch][] = "https://www.drupal.org/files/issues/2652138-28.patch"
projects[drupal][patch][] = "https://www.drupal.org/files/issues/2765525-30-8.2.x.patch"
projects[drupal][patch][] = https://www.drupal.org/files/issues/2655104-39.patch
