<?php
/**
 * @file
 * Code for the DFS WEM Personalize feature.
 */

include_once 'dfs_wem_personalize.features.inc';

// Global to be used for gathering target ids.
$_SESSION['wem-reference-queue'] = array();

/**
 * Implements hook_entity_insert().
 */
function dfs_wem_personalize_entity_insert($entity, $type) {

  // Set up new bean data with empty reference field.
  $data = array(
    'label' => 'WEM - Personalized Content',
    'description' => NULL,
    'title' => 'Nexus Contest',
    'type' => 'df_engage_block',
    'data' => array(
      'view_mode' => 'default',
    ),
    'delta' => 'wem---personalized-content',
    'view_mode' => 'default',
    'created' => 1403109793,
    'log' => '',
    'uid' => 1,
    'default_revision' => 1,
    'revisions' => array(),
    'vuuid' => '7390e524-cbe8-412c-95d1-6c9c58f83439',
    'uuid' => '5c35e68a-c593-4f50-937c-880910d83c78',
    'field_content_reference' => array('und' => array()),
  );

  // List the UUIDs for our desired referenced content.
  $content_uuids = array(
    '766cba85-2213-444c-a9c2-c7dd890142v7',
    '088bff85-6697-4a6a-bfe9-c7fa326282c8',
    'd4963a0f-75e3-44ba-9bd4-2c6b1cfaf676',
  );

  // Add the inserted content to the reference queue if its a match.
  if ($type == 'node' && in_array($entity->uuid, $content_uuids)) {
    $_SESSION['wem-reference-queue'][] = array('target_id' => $entity->nid);
    // Once all content is stored in the queue, add to the bean data.
    if (count($_SESSION['wem-reference-queue']) === count($content_uuids)) {
      $data['field_content_reference']['und'] = $_SESSION['wem-reference-queue'];
      // Check if bean already exists.
      $existing = entity_get_id_by_uuid('bean', array($data['uuid']));
      if (!empty($existing)) {
        // Load existing bean and re-key the values.
        $bean = entity_load_single('bean', $existing[$data['uuid']]);
        foreach ($data as $key => $value) {
          $bean->$key = $value;
        }
      }
      else {
        // Create a new bean.
        $bean = entity_create('bean', $data);
      }
      // Save the bean.
      if ($bean->save()) {
        // Tell us all about it.
        drupal_set_message(t('@title bean saved.', array('@title' => $data['label'])), 'status');
      }
      // Clear the queue for potential reuse.
      unset($_SESSION['wem-reference-queue']);
      $_SESSION['wem-reference-queue'] = array();
    }
  }

}

