<?php
/**
 * @file
 * Code for the DF Admin feature.
 */

include_once 'df_admin.features.inc';

/**
 * Implements hook_menu().
 */
function df_admin_menu() {
  $items['admin/config/system/df'] = array(
    'title' => 'Demo Framework',
    'description' => 'Manage Demo Framework Scenarios and configurations.',
    'page callback' => 'df_admin_page',
    'page arguments' => array(),
    'access arguments' => array('administer demo framework'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'df_admin.page.inc',
  );
  $items['admin/config/system/df/enable/%'] = array(
    'page callback' => 'df_admin_page_enable',
    'page arguments' => array(5),
    'access arguments' => array('administer demo framework'),
    'type' => MENU_CALLBACK,
    'file' => 'df_admin.enable.inc',
  );
  $items['admin/config/system/df/reset/%'] = array(
    'page callback' => 'df_admin_page_reset',
    'page arguments' => array(5),
    'access arguments' => array('administer demo framework'),
    'type' => MENU_CALLBACK,
    'file' => 'df_admin.reset.inc',
  );
  return $items;
}

/**
 * Implements hook_theme().
 */
function df_admin_theme(){
  return array(
    'df_admin_page_template' => array(
      'template' => 'df-admin-page',
      'variables' => array('scenarios' => NULL),
    ),
  );
}

