<?php

/**
 * @file
 * Contains dfs_tec.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dfs_tec_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dfs_dev module.
    case 'help.page.dfs_tec':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Demo Framework Scenario for Technology Websites.') . '</p>';
      return $output;
    default:
  }
}

/**
 * Implements hook_theme().
 */
function dfs_tec_theme() {
  $theme = [];
  return $theme;
}

/**
 * Implements hook_scenario_import().
 */
function dfs_tec_scenario_import() {
  $migrations = [];
  $migrations['dfs_tec'] = array(
    'import_dfs_tec_tags',
    'import_dfs_tec_article',
    'import_dfs_tec_basic',
    'import_dfs_tec_employee',
    'import_dfs_tec_image',
    'import_dfs_tec_page',
    'import_dfs_tec_service',
    'import_dfs_tec_hero',
    'import_dfs_tec_slideshow',
  );
  return (array) $migrations;
}
