<?php

/**
 * @file
 * Support for locations.
 */

use Drupal\field\Entity\FieldConfig;

/**
 * Implements hook_modules_installed().
 */
function df_tools_locations_modules_installed(array $modules) {
  // Don't do anything during config sync.
  if (\Drupal::isConfigSyncing()) {
    return;
  }

  // Add support for Acquia DAM Asset media entities to the Media field if the
  // df_tools_media_acquiadam module is installed.
  if (in_array('df_tools_media_acquiadam', $modules)) {
    // Retrieve the location's 'media' field.
    $instance = FieldConfig::loadByName('node', 'location', 'field_image');

    // Add 'acquia_dam_asset' to the list of allowed target bundles.
    $settings = $instance->getSetting('handler_settings');
    $settings['target_bundles'][] = 'acquia_dam_asset';
    $instance->setSetting('handler_settings', $settings);
    $instance->save();
  }
}




