<?php

/**
 * @file
 * Contains install and update routines for df_tools_workflow.
 */

/**
 * Implements hook_install().
 */
function df_tools_workflow_install() {
  // Don't do anything during config sync.
  if (\Drupal::isConfigSyncing()) {
    return;
  }

  // Grant existing roles the ability to moderation content.
  if (\Drupal::moduleHandler()->moduleExists('df_tools_user')) {
    df_tools_workflow_modules_installed(['df_tools_user']);
  }
}
