<?php

/**
 * @file
 * Contains df_tools_scheduler.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function df_tools_scheduler_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the df_tools_services module.
    case 'help.page.df_tools_scheduler':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A simplified version of the Scheduler module.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_cron().
 */
function df_tools_scheduler_cron() {
  // Check for nodes that need to be unpublished.
  $nids = \Drupal::entityQuery('node')
    ->condition('field_unpublish_on', date('Y-m-d 00:00:00'), '<=')
    ->execute();
  foreach ($nids as $nid) {
    $node = \Drupal\node\Entity\Node::load($nid);
    $node->setPublished(NODE_NOT_PUBLISHED);
    $node->set('field_unpublish_on', NULL);
    $node->save();
  }

  // Check for nodes that need to be published.
  $nids = \Drupal::entityQuery('node')
    ->condition('field_publish_on', date('Y-m-d 00:00:00'), '<=')
    ->execute();
  foreach ($nids as $nid) {
    $node = \Drupal\node\Entity\Node::load($nid);
    $node->setPublished(NODE_PUBLISHED);
    $node->set('field_publish_on', NULL);
    $node->save();
  }
}
