<?php

use Drupal\panels\Plugin\DisplayVariant\PanelsDisplayVariant;

/**
 * Implements hook_library_info_alter().
 */
function df_tools_frontend_library_info_alter(&$libraries, $extension) {
  if ($extension == 'image') {
    $path = drupal_get_path('module', 'df_tools_frontend');
    $libraries['quickedit.inPlaceEditor.image']['js']['/' . $path . '/js/quickedit_image_browser.js'] = [];
  }
  else if ($extension === 'lightning_media') {
    $path = drupal_get_path('module', 'df_tools_frontend');
    $libraries['browser.styling']['css']['component']['/' . $path . '/css/lightning_media.css'] = [];
  }
}

/**
 * Implements hook_panels_build_alter().
 */
function df_tools_frontend_panels_build_alter(&$build, PanelsDisplayVariant $panels_display) {
  $builder = $panels_display->getBuilder();

  if ($builder->getPluginId() === 'ipe' && isset($build['#attached']) && in_array('panels_ipe/panels_ipe', $build['#attached']['library'], TRUE)) {
    $build['#attached']['library'][] = 'df_tools_frontend/panels_ipe';
  }
}
