<?php

use Drupal\user\Entity\User;

/**
 * @file
 * Contains core functionality for the DF distribution.
 */

/**
 * Implements hook_module_implements_alter().
 *
 * @todo Remove after #2635978 is fixed.
 */
function df_core_module_implements_alter(&$implementations, $hook) {
  // Disable block initialization/inheritance for themes enabled after Lightning
  // is installed in order to prevent blocks associated with the profile from
  // bleeding over into scenarios.
  if ($hook == 'themes_installed') {
    unset($implementations['block']);
  }

  // Lightning attempts to automatically populate any empty path fields on
  // entities when they are loaded. This currently causes issues with Commerce
  // so we disable it for now.
  if ($hook == 'entity_load') {
    unset($implementations['lightning_core']);
  }
}

/**
 * Implements hook_form_alter().
 */
function df_core_form_alter(array &$form) {
  if (isset($form['scheduled_update']) && !\Drupal::currentUser()->hasPermission('schedule publishing of nodes')) {
    $form['scheduled_update']['#access'] = false;
  }
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function df_core_menu_local_tasks_alter(&$data, $route_name) {
  // Core doesn't currently clean up local tasks created via Views when the View
  // is disabled/deleted. Remove the core file listing view's local tasks in
  // order to prevent duplicate 'Files' tabs from appear on admin/content.
  // @todo: remove this when https://www.drupal.org/node/2027043 is fixed.
  if (!empty($data['tabs'])) {
    foreach ($data['tabs'] as $tab_level => $tabs) {
      foreach ($tabs as $href => $tab_data) {
        if ($href == 'views_view:view.files.page_1') {
          $data['tabs'][$tab_level][$href]['#access'] = FALSE;
        }
      }
    }
  }
}