<?php
/**
 * @file
 * Code for the DF Engage feature.
 */

include_once 'df_engage.features.inc';

/**
 *  Implements hook_post_features_enable_feature().
 */
function df_engage_post_features_enable_feature($component) {
  // Log components as they are enabled.
  watchdog('component', 'df_engage enabled ' . $component . ' component');
}

/**
 * Implements hook_migrate_api().
 */
function df_engage_migrate_api() {
  $api = array(
    'api' => 2,
    'migrations' => array(
      'DemoFrameworkBaseGroups' => array('class_name' => 'DemoFrameworkBaseGroups'),
      'DemoFrameworkBaseNodesGroup' => array('class_name' => 'DemoFrameworkBaseNodesGroup'),
      'DemoFrameworkBaseNodesUUID' => array('class_name' => 'DemoFrameworkBaseNodesUUID'),
    ),
  );
  return $api;
}

/**
 * Implements hook_bean_types_api_info().
 */
function df_engage_bean_types_api_info() {
  return array('api' => 4);
}

/**
 * Implements hook_bean_types().
 */
function df_engage_bean_types() {
  $plugins = array();
  $plugin_path = drupal_get_path('module', 'df_engage') . '/plugins';
  $plugins['df_engage_block'] = array(
    'label' => t('Engage'),
    'description' => t('A block used for personalization and testing.'),
    'handler' => array(
      'class' => 'EngageBlock',
      'parent' => 'bean',
    ),
    'path' => $plugin_path,
    'file' => 'EngageBlock.class.php',
  );
  return $plugins;
}

