<?php

/**
 * Implements hook_plugin_filter_TYPE__CONSUMER_alter().
 */
function df_tools_layout_plugin_filter_layout__layout_builder_alter(array &$definitions, array $extra) {
  // Remove layouts provided by other modules.
  $extra_layouts = [
    'layout_onecol',
    'layout_twocol_section',
    'layout_threecol_section',
    'layout_fourcol_section',
    'lightning_twocol',
    'lightning_threecol_25_50_25',
    'lightning_threecol_33_34_33',
    'moderation_dashboard',
  ];

  foreach ($extra_layouts as $extra_layout) {
    /** @var \Drupal\Core\Layout\LayoutDefinition[] $definitions */
    unset($definitions[$extra_layout]);
  }
}
