<?php
/**
 * @file
 * Code for the DFS_WEM feature.
 */

include_once 'dfs_wem.features.inc';

/**
 * Implements hook_behat_info().
 */
function dfs_wem_behat_info() {
  $info = array(
    'paths' => array(
      'features' => 'features',
    ),
  );
  return $info;
}

/**
 * Implements hook_migrate_api().
 */
function dfs_wem_migrate_api() {
  $api = array(
    'api' => 2,
    'migrations' => array(
      'DFSWEMGroupsWEMContestUsers' => array('class_name' => 'DFSWEMGroupsWEMContestUsers'),
      'DFSWEMContestNodes' => array('class_name' => 'DFSWEMContestNodes'),
      'DFSWEMContestNodesTranslations' => array('class_name' => 'DFSWEMContestNodesTranslations'),
      'DFSWEMCommerceNodes' => array('class_name' => 'DFSWEMCommerceNodes'),
      'DFSWEMCommerceNodesTranslations' => array('class_name' => 'DFSWEMCommerceNodesTranslations'),
      'DFSWEMInterestsTerms' => array('class_name' => 'DFSWEMInterestsTerms'),
      'DFSWEMNewsNodes' => array('class_name' => 'DFSWEMNewsNodes'),
      'DFSWEMNewsNodesTranslations' => array('class_name' => 'DFSWEMNewsNodesTranslations'),
      'DFSWEMNewsVideo' => array('class_name' => 'DFSWEMNewsVideo'),
      'DFSWEMPersonaTerms' => array('class_name' => 'DFSWEMPersonaTerms'),
      'DFSWEMProducts' => array('class_name' => 'DFSWEMProducts'),
      'DFSWEMProductReviewNodes' => array('class_name' => 'DFSWEMProductReviewNodes'),
      'DFSWEMSiteSectionTerms' => array('class_name' => 'DFSWEMSiteSectionTerms'),
      'DFSWEMTweetNodes' => array('class_name' => 'DFSWEMTweetNodes'),
      'DFSWEMUserPictures' => array('class_name' => 'DFSWEMUserPictures'),
      'DFSWEMUsers' => array('class_name' => 'DFSWEMUsers'),
    ),
  );
  return $api;
}

/**
 * Implements hook_df_import_alter().
 */
function dfs_wem_df_import_alter(&$migrations) {
  return $migrations['dfs_wem'] = array(
    'DFSWEMInterestsTerms',
    'DFSWEMPersonaTerms',
    'DFSWEMSiteSectionTerms',
    'DFSWEMUserPictures',
    'DFSWEMProducts',
    'DFSWEMCommerceNodes',
    'DFSWEMCommerceNodesTranslations',
    'DFSWEMUsers',
    'DFSWEMProductReviewNodes',
    'DFSWEMContestNodes',
    'DFSWEMContestNodesTranslations',
    'DFSWEMGroupsWEMContestUsers',
    'DFSWEMNewsVideo',
    'DFSWEMNewsNodes',
    'DFSWEMNewsNodesTranslations',
    'DFSWEMTweetNodes',
  );
}

/**
 *  Implements hook_post_features_enable_feature().
 */
function dfs_wem_post_features_enable_feature($component) {
  // Log components as they are enabled.
  watchdog('component', 'dfs_wem enabled ' . $component . ' component');
  if ($component == 'features_api') {
    migrate_get_module_apis();
  }
}

/**
 * Implements hook_entity_info_alter().
 */
function dfs_wem_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['redirect'] = array(
    'label' => t('Redirect'),
    'custom settings' => TRUE,
  );
}

