<?php

/**
 * @file
 * Installation routines for DFS_WEM feature
 */

/**
 * Implements hook_install().
 */
function dfs_wem_install() {
  // Enable custom theme on install.
  theme_enable(array('demonstratie_lce'));
  variable_set('theme_default', 'demonstratie_lce');

  // Set DFS WEM Home as the default homepage on install.
  variable_set('site_frontpage', 'dfs-wem-home');

  // Do not attach any sample orders for users.
  variable_set('df_commerce_add_sample_orders', FALSE);
}
