<?php
/**
 * @file
 * Code for the DF Tools Hero block feature.
 */

include_once 'df_tools_hero_block.features.inc';

/**
 * Implements hook_preprocess_entity().
 */
function df_tools_hero_block_preprocess_entity(&$variables) {
  if ($variables['entity_type'] == 'bean') {
    if ($variables['bean']->type == 'df_bean_hero') {
      $variables['classes_array'][] = 'hero';
    }
  }
}

/**
 * Implements hook_migrate_api
 */
function df_tools_hero_block_migrate_api() {
  $api = array(
    'api' => 2,
    'migrations' => array(
      'DFHeroBeans' => array('class_name' => 'DFHeroBeans', 'group_name' => 'df'),
    ),
  );
  return $api;
}


