<?php

/**
 * @file
 * Set up the Article content type for Demo Framework.
 */

/**
 * Implements hook_install().
 */
function df_tools_articles_install() {
  // Configure the Add To Any block for basic content types.
  $nodetypes = ['article' => 0, 'page' =>  0];
  \Drupal::configFactory()->getEditable('addtoany.settings')->set('nodetypes', $nodetypes)->save();

  // Enable translation for Articles.
  $entities = ['node' => ['article']];
  df_tools_translation_enable_translation($entities);
}
