<?php

/**
 * @file
 * Contains df_tools_gallery.module.
 */

/**
 * Implements hook_library_info_alter().
 */
function df_tools_gallery_library_info_alter(&$libraries, $extension) {
  // Optionally use the Libraries module to determine our library paths.
  if ($extension == 'df_tools_gallery' && \Drupal::moduleHandler()->moduleExists('libraries')) {
    $imagesloaded_path = libraries_get_path('imagesloaded') . '/imagesloaded.pkgd.min.js';
    $masonry_path = libraries_get_path('masonry') . '/dist/masonry.pkgd.min.js';

    $libraries['imagesloaded']['js'] = ['/' . $imagesloaded_path => ['minified' => 'true']];
    $libraries['masonry']['js'] = ['/' . $masonry_path => ['minified' => 'true']];
  }
}

/**
 * Implements hook_migration_plugins_alter().
 */
function df_tools_gallery_migration_plugins_alter(&$definitions) {
  $id = 'import_gallery_image';
  if (isset($definitions[$id])) {
    $definitions[$id]['source']['path'] = str_replace('..', dirname(__FILE__), $definitions[$id]['source']['path']);
  }
}
