<?php

/**
 * @file
 * Contains dfs_dev.module.
 */

/**
 * Implements hook_scenario_import().
 */
function dfs_dev_scenario_import() {
  $migrations = [];
  $migrations['dfs_dev'] = array(
    'import_block_basic',
    'import_block_hero',
    'import_block_map',
    'import_term_tags',
    'import_node_page',
    'import_node_article',
    'import_block_slideshow',
    'import_gallery_image',
  );
  return (array) $migrations;
}
