<?php

/**
 * @file
 * Set up the DEV Scenario.
 */

/**
 * Implements hook_install().
 */
function dfs_dev_install() {
  // Set front page to "dev-home".
  \Drupal::configFactory()->getEditable('system.site')->set('page.front', 'dev-home')->save();

  // Set the default theme to Zurb Foundation
  \Drupal::configFactory()->getEditable('system.theme')->set('default', 'zurb_foundation')->save();
}

/**
 * Implements hook_uninstall().
 */
function dfs_dev_uninstall() {
  // Set front page to "welcome".
  \Drupal::configFactory()->getEditable('system.site')->set('page.front', 'welcome')->save();
}

