<?php

/**
 * @file
 * Contains df_tools_cohesion.install.
 */

use Drupal\field\Entity\FieldConfig;

/**
 * Implements hook_install().
 */
function df_tools_cohesion_install() {
  $module_handler = \Drupal::moduleHandler();

  // Delete layout_builder__layout that ships with lightning_layout.
  if ($module_handler->moduleExists('lightning_layout')) {
    FieldConfig::loadByName('node', 'landing_page', 'layout_builder__layout')->delete();
  }
}
