<?php

/**
 * @file
 * Set up the One Scenario.
 */

/**
 * Implements hook_install().
 */
function dfs_one_install() {
  // Set front page to "home" and set site name to "One"
  \Drupal::configFactory()
    ->getEditable('system.site')
    ->set('page.front', '/home')
    ->set('name', "One")
    ->save(TRUE);

  // Clear cached info causing post-install class discovery errors.
  drupal_flush_all_caches();
}
