<?php

/**
 * @file
 * Contains df_tools_media.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\views\ViewEntityInterface;

/**
 * Implements hook_migration_plugins_alter().
 */
function df_tools_media_migration_plugins_alter(&$definitions) {
  $id = 'import_media_image';
  $definitions[$id]['source']['path'] = str_replace('..', dirname(__FILE__), $definitions[$id]['source']['path']);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function df_tools_media_form_entity_browser_media_browser_in_modal_form_alter(array &$form, FormStateInterface $form_state) {
  $form['#attached']['library'][] = 'lightning_media/browser.styling';
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function df_tools_media_views_insert(ViewEntityInterface $view) {
  if (\Drupal::isConfigSyncing()) {
    return;
  }
  elseif (drupal_installation_attempted() && $view->id() == 'media') {
    $display1 = &$view->getDisplay('entity_browser_1');
    $display2 = &$view->getDisplay('entity_browser_2');
    $display1['display_options']['filters']['field_tags_target_id'] = $display2['display_options']['filters']['field_tags_target_id'] = [
      'id' => 'field_tags_target_id',
      'table' => 'media__field_tags',
      'field' => 'field_tags_target_id',
      'relationship' => 'none',
      'group_type' => 'group',
      'admin_label' => '',
      'operator' => 'or',
      'value' => [],
      'group' => 1,
      'exposed' => true,
      'expose' => [
        'operator_id' => 'field_tags_target_id_op',
        'label' => 'Tags',
        'description' => '',
        'use_operator' => false,
        'operator' => 'field_tags_target_id_op',
        'identifier' => 'field_tags_target_id',
        'required' => false,
        'remember' => false,
        'multiple' => false,
        'remember_roles' => [
          'authenticated' => 'authenticated',
          'anonymous' => '0',
          'administrator' => '0',
          'layout_manager' => '0',
          'creator' => '0',
          'reviewer' => '0',
          'media_creator' => '0',
          'media_manager' => '0',
        ],
        'reduce' => false,
      ],
      'is_grouped' => false,
      'group_info' => [
        'label' => '',
        'description' => '',
        'identifier' => '',
        'optional' => true,
        'widget' => 'select',
        'multiple' => false,
        'remember' => false,
        'default_group' => 'All',
        'default_group_multiple' => [],
        'group_items' => [],
      ],
      'reduce_duplicates' => false,
      'type' => 'textfield',
      'limit' => true,
      'vid' => 'media_tags',
      'hierarchy' => false,
      'error_message' => true,
      'plugin_id' => 'taxonomy_index_tid',
    ];
    $view->save();
  }
}

