<?php

/**
 * @file
 * Set up the Landing Page content type for Demo Framework.
 */

use Drupal\shortcut\Entity\Shortcut;

/**
 * Implements hook_install().
 */
function df_tools_landing_install() {
  // Add Ladning Page to the default shortcut set.
  $shortcut = Shortcut::create('shortcut', array(
    'shortcut_set' => 'default',
    'title' => t('Add Landing Page'),
    'weight' => -3,
    'link' => array('uri' => 'internal:/node/add/landing_page'),
  ));
  $shortcut->save();
}
