<?php

/**
 * @file
 * Contains install and update routines for df_tools_scheduled_updates.
 */

/**
 * Implements hook_install().
 */
function df_tools_scheduled_updates_install() {
  // Don't do anything during config sync.
  if (\Drupal::isConfigSyncing()) {
    return;
  }

  // Grant existing roles the ability to schedule content updates.
  if (\Drupal::moduleHandler()->moduleExists('df_tools_user')) {
    df_tools_scheduled_updates_modules_installed(['df_tools_user']);
  }
}
