<?php
/**
 * @file
 * Code for the DFS_Workflow feature.
 */

include_once 'dfs_dm.features.inc';

/**
 * Implements hook_migrate_api().
 */
function dfs_dm_migrate_api() {
  $api = array(
    'api' => 2,
    'migrations' => array(
      'DFSDMTermsIds' => array('class_name' => 'DFSDMTermsIds'),
      'DFSDMUsers' => array('class_name' => 'DFSDMUsers'),
    ),
  );
  return $api;
}

/**
 * Implements hook_df_import_alter().
 */
function dfs_dm_df_import_alter(&$migrations) {
  return $migrations['dfs_dm'] = array(
    'DFSDMTermsIds',
    'DFSDMUsers',
  );
}

/**
 *  Implements hook_post_features_enable_feature().
 */
function dfs_dm_post_features_enable_feature($component) {
  // Log components as they are enabled.
  watchdog('component', 'dfs_dm enabled ' . $component . ' component');
}

