<?php


/**
 * Implements hook_migration_plugins_alter().
 */
function df_tools_map_migration_plugins_alter(&$definitions) {
  // Set up base path.
  $path = dirname(__FILE__) . '/data/';

  // Add our block migrations
  $types = [
    'map' => [
      'columns' => [
        2 => 'Address Line 1',
        3 => 'Address Line 2',
        4 => 'Address City',
        5 => 'Address State',
        6 => 'Address Zip',
      ],
      'fields' => [
        'field_address/langcode' => [
          'plugin' => 'default_value',
          'default_value' => 'en'
        ],
        'field_address/country_code' => [
          'plugin' => 'default_value',
          'default_value' => 'US'
        ],
        'field_map_address/address_line1' => 'Address Line 1',
        'field_map_address/address_line2' => 'Address Line 2',
        'field_map_address/locality' => 'Address City',
        'field_map_address/administrative_area' => 'Address State',
        'field_map_address/postal_code' => 'Address Zip',
        'field_map_address/recipient' => 'Info',
        'field_map_geofield' => 'Geofield',
      ]
    ],
  ];
  foreach ($types as $type => $info) {
    $migration = _df_migration_copy($definitions['import_block_base'], 'block', $type, 'block_content', $path);
    // Add our custom fields.
    _df_migration_fields($migration, $info['columns'], $info['fields']);
    // Add our custom plugins.
    $migration['source']['plugin'] = $type . '_block';
    // Save the new migration.
    $definitions[$migration['id']] = $migration;
  }
}
