<?php

/**
 * @file
 * Set up the DF Tools Slideshow base migrations.
 */

/**
 * Implements hook_migration_plugins_alter().
 */
function df_tools_slideshow_migration_plugins_alter(&$definitions) {
  // Set up base path.
  $path = dirname(__FILE__) . '/data/';

  $migration = _df_migration_copy($definitions['import_block_base'], 'block', 'slideshow', 'block_content', $path);
  // Add our custom fields.
  _df_migration_fields($migration, [2 => 'Slides'], ['field_block' => 'Slides']);
  // Add our custom plugins.
  $migration['source']['plugin'] = 'slideshow_block';
  // Save the new migration.
  $definitions[$migration['id']] = $migration;
}
