<?php

/**
 * @file
 * Contains df_tools_slideshow.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function df_tools_slideshow_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the df_tools_slideshow module.
    case 'help.page.df_tools_slideshow':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides a Slideshow block type.') . '</p>';
      return $output;

    default:
  }
}
