<?php
/**
 * @file
 * Code for the df_curator feature.
 */

include_once 'df_curator.features.inc';

/**
 *  Implements hook_post_features_enable_feature(). 
 */
function df_curator_post_features_enable_feature($component) {
  // Log components as they are enabled.
  watchdog('component', 'df_curator enabled ' . $component . ' component');
}

/**
 * Implements hook_block_list_alter().
 *
 * This is an override for the Edit module.
 * See: https://drupal.org/node/2029783
 */
function df_curator_block_list_alter(&$blocks) {
  foreach ($blocks as $block) {
    if ($block->delta == 'edit') {
      $blocks[$block->bid]->region = '';
    }
  }
  return $blocks;
}

/**
 * Implements hook_entity_info_alter().
 */
function df_curator_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['alternate'] = array(
    'label' => t('Alternate'),
    'custom settings' => TRUE,
  );
}

