<?php

/**
 * @file
 * Contains df_tools_moderation.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\node\Entity\Node;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function df_tools_moderation_form_workbench_moderation_entity_moderation_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $form['#submit'][] = 'df_tools_moderation_workbench_moderation_entity_moderation_form_submit';
}

/**
 * Form submission callback for workbench_moderation_entity_moderation_form.
 */
function df_tools_moderation_workbench_moderation_entity_moderation_form_submit($form, FormStateInterface $form_state) {
  /** @var ContentEntityInterface $entity */
  $entity = $form_state->get('entity');

  $new_state = $form_state->getValue('new_state');

  // When creating a new draft, redirect the user to the latest version of the
  // content.
  if ($new_state == 'draft') {
    $form_state->setRedirectUrl($entity->toUrl('latest-version'));
  }
}

/**
 * Implements hook_menu_local_tasks_alter();
 */
function df_tools_moderation_menu_local_tasks_alter(&$data, $route_name) {
  // Runs when cache tag config:block.block.[ActiveTheme]_local_actions is invalidated.
  if (isset($data['tabs'][0]['moderation_state.entities:node.latest_version_tab'])) {
    $url = $data['tabs'][0]['moderation_state.entities:node.latest_version_tab']['#link']['url'];
    $param = $url->getRouteParameters();
    if (isset($param['node'])) {
      $node = Node::load($param['node']);
      $moderation_info = \Drupal::service('workbench_moderation.moderation_information');
      $latest_node = $moderation_info->getLatestRevision('node', $node->id());
      // Modify the tabs when the canonical route is the latest revision.
      if ($latest_node->getRevisionId() == $node->getRevisionId()) {
        // Highlight the 'View' tab at /node/%/latest.
        if ($data['tabs'][0]['moderation_state.entities:node.latest_version_tab']['#active']) {
          $data['tabs'][0]['entity.node.canonical']['#active'] = true;
        }
        // Remove the latest version tab.
        unset($data['tabs'][0]['moderation_state.entities:node.latest_version_tab']);
      }
    }
  }
}
