<?php

/**
 * @file
 * Integrates the Lite track changes plugin for CKEditor with Demo Framework.
 */

/**
 * Implements hook_filter_default_formats_alter().
 */
function df_tools_cklite_filter_default_formats_alter(&$formats) {
  if (!empty($formats['filtered_html'])) {
    $editor_settings = unserialize($formats['filtered_html']['editor_settings']);

    // Add a new group containing the Lite buttons to the first toolbar row.
    $editor_settings['toolbar'][0][] = array(
      'name' => 'Lite',
      'items' => array(
        0 => 'lite-toggletracking',
        1 => 'lite-toggleshow',
        2 => 'lite-acceptall',
        3 => 'lite-rejectall',
        4 => 'lite-acceptone',
        5 => 'lite-rejectone',
      ),
    );

    $formats['filtered_html']['editor_settings'] = serialize($editor_settings);
  }
}
